// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs_vCappGKQXmXFFxxESvzFgmQzggPROw',
    appId: '1:1066906703890:web:24ce848caa1ce83c2060cb',
    messagingSenderId: '1066906703890',
    projectId: 'project1682-ff536',
    authDomain: 'project1682-ff536.firebaseapp.com',
    storageBucket: 'project1682-ff536.appspot.com',
    measurementId: 'G-QY66R1M495',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ2f3cJrd8mkWJfLTA3hOnyKsdKIs1NAs',
    appId: '1:1066906703890:android:2dd06c82d3040f622060cb',
    messagingSenderId: '1066906703890',
    projectId: 'project1682-ff536',
    storageBucket: 'project1682-ff536.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy1M-dD7NLv1Eok4sTBuSnWhttTJ6TP7I',
    appId: '1:1066906703890:ios:3e2267ec2624754b2060cb',
    messagingSenderId: '1066906703890',
    projectId: 'project1682-ff536',
    storageBucket: 'project1682-ff536.appspot.com',
    iosClientId: '1066906703890-ts8anem36aecmrievrmcon9cv9dqvrek.apps.googleusercontent.com',
    iosBundleId: 'vn.project1682.chatappFirebase',
  );
}
